name: Cloudflare Pagesへデプロイ

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: minify
        working-directory: ./frontend
        run: |
          npm install html-minifier -g
          mkdir dist
          npx html-minifier \
            --collapse-whitespace \
            --remove-comments \
            --minify-css true \
            --minify-js true \
            -o dist/index.html \
            index.html
          
          npm install clean-css-cli -g
          npx cleancss -o dist/styles.css styles.css

      - name: deploy
        working-directory: ./frontend
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
        run: |
          npm install wrangler -g
          npx wrangler pages deploy dist --project-name http2kb
